# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# BufferAndClip.py
# Created on: 2014-10-20 16:35:06.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: BufferAndClip <Input_Feature_Class> <Clip_Feature_Class> <Clipped_Output> 
# Description: 
# Used for an exercise in Module 4.
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_Feature_Class = arcpy.GetParameterAsText(0)

Clip_Feature_Class = arcpy.GetParameterAsText(1)

Clipped_Output = arcpy.GetParameterAsText(2)
if Clipped_Output == '#' or not Clipped_Output:
    Clipped_Output = "C:\\Users\\scrook\\Desktop\\Lab7-sc\\Geoprocess\\Geoprocess\\More\\Florida\\StudyArea.gdb\\BufferTemp_Clip" # provide a default value if unspecified

# Local variables:
Buffered_Output = "C:\Users\scrook\Desktop\Lab7-sc\Geoprocess\Geoprocess\More\Florida\StudyArea.gdb\BufferTemp"

# Process: Buffer
arcpy.Buffer_analysis(Input_Feature_Class, Buffered_Output, "100 Meters", "FULL", "ROUND", "NONE", "")

# Process: Clip
arcpy.Clip_analysis(Buffered_Output, Clip_Feature_Class, Clipped_Output, "")

